name: Aider PR Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  trigger-aider-workflow:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/aider')
    uses: tomasmcm/threads-clone/.github/workflows/aider-issue-to-pr.yml@main
    with:
      pr-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.pull_request.base.ref }}
      comment-body: ${{ github.event.comment.body }}
      model: 'claude-3-5-sonnet-20240620'
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}