name: Aider PR Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  get-pr-details:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/aider')
    runs-on: ubuntu-latest
    outputs:
      base_branch: ${{ steps.pr_details.outputs.base_branch }}
    steps:
      - name: Get PR details
        id: pr_details
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });
            core.setOutput('base_branch', pr.data.base.ref);

  trigger-aider-workflow:
    needs: get-pr-details
    uses: tomasmcm/threads-clone/.github/workflows/aider-issue-to-pr.yml@main
    with:
      pr-number: ${{ github.event.issue.number }}
      base-branch: ${{ needs.get-pr-details.outputs.base_branch }}
      comment-body: ${{ github.event.comment.body }}
      model: 'claude-3-5-sonnet-20240620'
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}