name: Aider PR Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  trigger-aider-workflow:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/aider') }}
    uses: tomasmcm/threads-clone/.github/workflows/aider-pr-update.yml@main
    with:
      pr-number: ${{ github.event.issue.number }}
      comment: ${{ github.event.comment.body }}
      model: 'claude-3-5-sonnet-20241022'
    secrets: 
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}