name: Aider PR Comment Workflow
on:
  issue_comment:
    types: [created]

jobs:
  process-pr-comment:
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Check if comment is from a collaborator
        id: check_collaborator
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const username = context.payload.comment.user.login;
            
            try {
              const { data: collaboratorStatus } = await github.rest.repos.checkCollaborator({
                owner,
                repo,
                username,
              });
              return collaboratorStatus;
            } catch (error) {
              if (error.status === 404) {
                return false;
              }
              throw error;
            }
      - name: Get PR details and prepare inputs
        if: steps.check_collaborator.outputs.result == 'true'
        id: pr_details
        uses: actions/github-script@v7
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { repo, owner } = context.repo;
            const comment = context.payload.comment.body;
            
            if (comment.toLowerCase().startsWith('/aider')) {
              const pr = await github.rest.pulls.get({
                owner,
                repo,
                pull_number: context.issue.number
              });
              
              const commentBody = comment.substring(6).trim(); // Remove '/aider' and trim whitespace
              
              return {
                baseBranch: pr.data.base.ref,
                prNumber: context.issue.number.toString(),
                commentBody: commentBody
              };
            }
            return null;

  trigger-aider-workflow:
    needs: process-pr-comment
    if: needs.process-pr-comment.outputs.pr_details
    uses: tomasmcm/threads-clone/.github/workflows/aider-issue-to-pr.yml@main
    with:
      base-branch: ${{ fromJSON(needs.process-pr-comment.outputs.pr_details).baseBranch }}
      pr-number: ${{ fromJSON(needs.process-pr-comment.outputs.pr_details).prNumber }}
      comment-body: ${{ fromJSON(needs.process-pr-comment.outputs.pr_details).commentBody }}
      model: 'claude-3-5-sonnet-20240620'
    secrets:
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}