name: Aider Issue Trigger
on:
  issues:
    types: [labeled]

jobs:
  generate:
    uses: tomasmcm/threads-clone/.github/workflows/aider-issue-to-pr.yml@main
    if: github.event.label.name == 'aider'
    with:
      issue-number: ${{ github.event.issue.number }}
      base-branch: ${{ github.event.repository.default_branch }}
      model: 'anthropic/claude-3-5-sonnet-20241022'
    secrets: 
      anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
