name: Aider PR Comment Trigger
on:
  issue_comment:
    types: [created]

jobs:
  process-pr-comment:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/aider') }}
    runs-on: ubuntu-latest
    steps:
      - name: Get PR details
        id: pr_details
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const pr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: context.issue.number
            });
            return {
              head_sha: pr.data.head.sha,
              head_ref: pr.data.head.ref,
              base_ref: pr.data.base.ref
            };

      - name: Trigger Aider workflow
        uses: tomasmcm/threads-clone/.github/workflows/aider-pr-update.yml@main
        with:
          pr-number: ${{ github.event.issue.number }}
          base-branch: ${{ steps.pr_details.outputs.result.base_ref }}
          head-branch: ${{ steps.pr_details.outputs.result.head_ref }}
          head-sha: ${{ steps.pr_details.outputs.result.head_sha }}
          comment: ${{ github.event.comment.body }}
          model: 'claude-3-5-sonnet-20240620'
        secrets: 
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}